# freeCodeCamp - Python for Data Science - Course for Beginners
## https://www.youtube.com/watch?v=LHBE6Q9XlzI

This is my first program in Python. Wish me luck!

In [1]:
print("Hello, Kautzar!")

Hello, Kautzar!


$a=b+c$

In [4]:
a = 3 * 5
b = 7 - 2
print(a + b)

20


In [5]:
x = 2 # int 
y = 5 # int 
xy = 7.2 # float 
a, b = 4, 5.0 # multiple assignment 

print(x)
print(type(x))

print(y)
print(type(y))

print(xy)
print(type(xy))

print(a)
print(type(a))

print(b)
print(type(b))

2
<class 'int'>
5
<class 'int'>
7.2
<class 'float'>
4
<class 'int'>
5.0
<class 'float'>


In [6]:
del x 
print(x)

NameError: name 'x' is not defined

In [9]:
call_my_name = "Hey, Kautzar!"
print(call_my_name)
print(type(call_my_name))

number_as_string = "13"
print(number_as_string)
print(type(number_as_string))

Hey, Kautzar!
<class 'str'>
13
<class 'str'>


In [1]:
print(round(4.23456, 3))

4.235


In [7]:
a = True
b = False 
c = a and b
d = a or b

print(c)
print(d)
print(a == b)
print(a != b)

False
True
False
True


In [11]:
x = 27 
y = 5
print(divmod(x, y))
print(x//y)
print(x%y)

(5, 2)
5
2


# Numpy Python Data Science Library

In [10]:
import numpy as np
a = np.array([1,2,3,4,5])
b = np.array((1,6,3,4,9), dtype = "f")

print(a)
print(type(a))
print(b)
print(type(b))

[1 2 3 4 5]
<class 'numpy.ndarray'>
[1. 6. 3. 4. 9.]
<class 'numpy.ndarray'>


In [12]:
a.dtype;
b.dtype

dtype('float32')

# Numpy Dimensions

In [22]:
a = np.array([[1,2,3], [4,5,6]])
print(a.ndim)
print(a[0,2])
print(type(a))

2
3
<class 'numpy.ndarray'>


In [23]:
b = np.array([[[1,2,3],[4,5,6]], [[2,3,4],[5,6,7]]])
print(b.ndim)
print(b[1,1])
print(b.shape[0], b.shape[1], b.shape[2])
print(b[1,0,2])
print(type(b))

3
[5 6 7]
2 2 3
4
<class 'numpy.ndarray'>


# Covid19 Trend Analysis

In [27]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer

In [ ]:
df 